CREATE TABLE threads (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    forum_id INT NOT NULL,
    title TEXT NOT NULL,
    position INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bump INT NOT NULL,
    FOREIGN KEY (forum_id) REFERENCES forums(id) ON DELETE CASCADE
) ENGINE InnoDB;
